---
sudo: required
language: python
python: 2.7

services:
  - docker

install:
  - pip install ome-ansible-molecule-dependencies

script:
  - cd $PLAYBOOKDIR && molecule test

env:
  - PLAYBOOKDIR=one-node
  - PLAYBOOKDIR=public-user
  - PLAYBOOKDIR=three-nodes
