---
sudo: required
language: python

services:
  - docker

install:
  - pip install ome-ansible-molecule

script:
  - cd $PLAYBOOKDIR && molecule test

env:
  - PLAYBOOKDIR=ansible-example-omero-onenode
  - PLAYBOOKDIR=public-user
  - PLAYBOOKDIR=three-nodes

# Docker-only
# - PLAYBOOKDIR=docker-example-omero-websockets
