---

- src: openmicroscopy.postgresql
  version: 2.0.0

- src: openmicroscopy.omero-common

- name: openmicroscopy.omego

- name: openmicroscopy.omero-server

- name: openmicroscopy.omero-web

- name: omero-user
  src:  https://github.com/openmicroscopy/ansible-role-omero-user.git
  # TODO: workaround for missing owner
