---
- name: Prepare all
  hosts: all
  tasks:
  - name: Install netstat
    yum:
      pkg:
        # Required for Ansible network vars, missing from Docker image
        - iproute
      state: present
